### ISSUE TITLE
Styling Issue

### ISSUE THREAD

**Issue by paulushub** [RazrFalcon/resvg-test-suite#37]
Trying to create a styling file that be linked (where possible) or dynamically embedded in the SVG test files for consistent results. Does the following CSS captures the styling required by the tests? (**Inkscape** results later shows it can make a difference):
**NOTE:** Some of the font families like **NotoSans-Medium.ttf** are not currently included in the **fonts** directory.
```css
* { 
  font-family: "Noto Sans" 
}
.serif {
  font-family: "Noto Serif", serif;
}
.sansserif {
  font-family: "Noto Sans", sans-serif;
}
.monospace {
  font-family: "Noto Mono", monospace;
}
.cursive {
  font-family: "Yellowtail", cursive;
}
.fantasy {
  font-family: "Sedgwick Ave Display", fantasy;
}
.emoji {
  font-family: "Noto Color Emoji", "Noto Emoji", emoji;
}
.math {
  font-family: math;
}
.fangsong {
  font-family: fangsong;
}
@font-face {
   font-family: "Noto Serif";
   font-style: normal;
   font-weight: 400;
   src: url(../fonts/NotoSerif-Regular.ttf) format('truetype');
 }
@font-face {
  font-family: "Noto Sans";
  font-style: normal;
  font-weight: 100;
  src: url(../fonts/NotoSans-Thin.ttf) format('truetype');
}
@font-face {
  font-family: "Noto Sans";
  font-style: normal;
  font-weight: 200;
  src: url(../fonts/NotoSans-Light.ttf) format('truetype');
}
@font-face {
   font-family: "Noto Sans";
   font-style: normal;
   font-weight: 300;
   src: url(../fonts/NotoSans-DemiLight.ttf) format('truetype');
}
@font-face {
   font-family: "Noto Sans";
   font-style: normal;
   font-weight: 400;
   src: url(../fonts/NotoSans-Regular.ttf) format('truetype');
 }
@font-face {
   font-family: "Noto Sans";
   font-style: normal;
   font-weight: 500;
   src: url(../fonts/NotoSans-Medium.ttf) format('truetype');
 }
@font-face {
   font-family: "Noto Sans";
   font-style: normal;
   font-weight: 700;
   src: url(../fonts/NotoSans-Bold.ttf) format('truetype');
 }
@font-face {
   font-family: "Noto Sans";
   font-style: normal;
   font-weight: 900;
   src: url(../fonts/NotoSans-Black.ttf) format('truetype');
 }
@font-face {
   font-family: Yellowtail;
   font-style: normal;
   font-weight: 400;
   src: url(../fonts/Yellowtail-Regular.ttf) format('truetype');
 }
@font-face {
   font-family: "Sedgwick Ave Display";
   font-style: normal;
   font-weight: 400;
   src: url(../fonts/SedgwickAveDisplay-Regular.ttf) format('truetype');
 }
@font-face {
   font-family: "Source Sans Pro";
   font-style: normal;
   font-weight: 400;
   src: url(../fonts/SourceSansPro-Regular.ttf) format('truetype');
 }
@font-face {
   font-family: "Noto Color Emoji";
   font-style: normal;
   font-weight: 400;
   src: url(../fonts/NotoColorEmoji.ttf) format('truetype');
 }
@font-face {
   font-family: "Noto Emoji";
   font-style: normal;
   font-weight: 400;
   src: url(../fonts/NotoEmoji-Regular.ttf) format('truetype');
 }
@font-face {
   font-family: Amiri;
   font-style: normal;
   font-weight: 400;
   src: url(../fonts/Amiri-Regular.ttf) format('truetype');
 }
@font-face {
   font-family: MPLUS1p;
   font-style: normal;
   font-weight: 400;
   src: url(../fonts/MPLUS1p-Regular.ttf) format('truetype');
 }
```
**Update 1:** Added missing `@font-face` definition for `Noto Serif`.

The following are the results generated by exporting **a-alignment-baseline-001.svg** with **Inkscape** (command line)
Without Styling (current default) | With Styling (above css embedded)
-----------------------------------------|----------------------------------------------
<img src="https://user-images.githubusercontent.com/809351/126042942-8d42c8f0-80af-4554-a264-6177d717a252.png" /> |  <img src="https://user-images.githubusercontent.com/809351/126042975-90325b3d-3539-4bb1-bd6f-13afe998dafa.png" />

**Comment by RazrFalcon** [comment]
I don't any app except browsers does support `@font-face`. So this will not be universal anyway.

To get the expected results, you have to simply install those fonts. That's it.

**Comment by paulushub** [comment]
> I don't think any app except browsers does support @font-face. So this will not be universal anyway.

Below is the result for **Batik 1.14**, I think most libraries with complete CSS support implements `@font-face`. Installation does not map for generic fonts like `serif`, `monospace` etc.

Without Styling (current default) | With Styling (above css embedded)
-----------------------------------------|----------------------------------------------
<img src="https://user-images.githubusercontent.com/809351/126056367-b0d4bae6-7728-4ce6-a940-5b578eb2cdf5.png" /> |  <img src="https://user-images.githubusercontent.com/809351/126056369-e5590468-025c-409a-8d49-acccdd1ea0bb.png" />

**Comment by RazrFalcon** [comment]
Are you sure? I've just tested this file:

```xml
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <title>Simple case</title>

    <style>
        .fantasy {
            font-family: "Sedgwick Ave Display", fantasy;
        }
        @font-face {
            font-family: "Sedgwick Ave Display";
            font-style: normal;
            font-weight: 400;
            src: url(../fonts/SedgwickAveDisplay-Regular.ttf) format('truetype');
         }
    </style>

    <path id="crosshair" d="M 20 100 L 180 100 M 100 20 L 100 180"
          stroke="gray" stroke-width="0.5"/>

    <text id="text1" x="32" y="100" font-family="fantasy" font-size="64">Text</text>

    <!-- image frame -->
    <rect id="frame" x="1" y="1" width="198" height="198" fill="none" stroke="black"/>
</svg>
```

And all applications, even browsers, ignored it.

**Comment by RazrFalcon** [comment]
>Installation does not map for generic fonts like serif, monospace etc.

Yes, you just have to check those tests manually. Testing cannot be automated anyway.

**Comment by paulushub** [comment]
> And all applications, even browsers, ignored it.

True, however, the issue here requires a bit more investigation. 
I used a different fantasy font, **Old English Text MT** (installed on my system) and it does not work in any browser and even in the **Resvg** (if you do not specify the --fantasy-family on the commandline).
```css
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <title>Simple case</title>

    <style>
		.fantasy {
			font-family: "Old English Text MT", fantasy;
		}
    </style>

    <path id="crosshair" d="M 20 100 L 180 100 M 100 20 L 100 180"
          stroke="gray" stroke-width="0.5"/>

    <text id="text1" x="32" y="100" font-family="fantasy" font-size="48">Text</text>

    <!-- image frame -->
    <rect id="frame" x="1" y="1" width="198" height="198" fill="none" stroke="black"/>
</svg>
```
I also tried **Papyrus** for the fantasy font and it fails! 
For **Resvg**, even setting **Papyrus** directly fails, but works in all browsers.
```css
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <title>Simple case</title>

    <path id="crosshair" d="M 20 100 L 180 100 M 100 20 L 100 180"
          stroke="gray" stroke-width="0.5"/>

    <text id="text1" x="32" y="100" font-family="Papyrus" font-size="48">Text</text>

    <!-- image frame -->
    <rect id="frame" x="1" y="1" width="198" height="198" fill="none" stroke="black"/>
</svg>

```
